### ISSUE TITLE
Problem installing requirements

### ISSUE THREAD

**Issue by Findarato** [robertdebock/ansible-role-awx#1]
**Describe the bug**

**Playbook**
Please paste the playbook you are using. (Consider `requirements.yml` and
optionally the command you've invoked.)

```yaml

- hosts: awx
  gather_facts: true
  become: true
  roles:
    # - geerlingguy.git
    # - robertdebock.ansible
    # - robertdebock.bootstrap
    # - robertdebock.buildtools
    # - robertdebock.core_dependencies
    # - robertdebock.docker_ce
    # - robertdebock.epel
    # - robertdebock.python_pip
    - robertdebock.awx
  post_tasks:
  pre_tasks:
  vars_files:
    - "vars/main.yml"
    - "vars/vault.yml"

```

**Output**
TASK [robertdebock.awx : install requirements on localhost] *******************************************
Sorry, try again.
FAILED - RETRYING: install requirements on localhost (3 retries left).
Sorry, try again.
FAILED - RETRYING: install requirements on localhost (2 retries left).
Sorry, try again.
FAILED - RETRYING: install requirements on localhost (1 retries left).
Sorry, try again.
fatal: [awx]: FAILED! => changed=false
  attempts: 3
  module_stderr: |-
    [sudo via ansible, key=taswmeexdxbqotmxrvjmcyfdvdilappw] password:
    sudo: no password was provided
    sudo: 1 incorrect password attempt
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

**Expected behavior**

**Environment**
- Fedora 31 -> CentOS 7.7

I have set an ansible_enable_pass but it seems to not be using it.
